### PR TITLE
feat(API): Unify return values of routes

### PR DESCRIPTION
**Pull request by ff6347**
This PR does some housekeeping on the api routes. Changes all return value keys to `data`

⚠️  BREAKING CHANGES: This will break some existing implementation in the frontend

### CODE REVIEW

**Review by vogelino — APPROVED** [review]
👍

**Comment by dnsos** [comment]
@ff6347 @vogelino, I took the liberty to change this in the frontend calls as well. The breaking changes should now be handled already.

**Comment by vogelino** [comment]
Could you already try if this works? @dnsos

**Comment by dnsos** [comment]
> Could you already try if this works?

Yes, it does!

**Pull request merged**
