### PR TITLE
docs(api): Extend docs about API and database [skip ci]

### PR DESCRIPTION
**Pull request by ff6347**
Minor edits on the docs. Does not touch any source code

### CODE REVIEW

**Comment by ff6347** [comment]
@vogelino @dnsos Can you tell why this fails? My branch was based on staging

**Comment by dnsos** [comment]
Hmm, we've had this issue before, remember @vogelino? I'm just surprised that we are encountering it again. I'm trying to remember what was the issue and I kind of recall a mismatch between our code and the installed Next/React types.

**Comment by vogelino** [comment]
@ff6347 & @dnsos There was an improper typing of the nextjs page. We have done that in a much cleaner way in the wegweiser project so I felt free to bring this logic to this project too. It should pass now.

**Comment by ff6347** [comment]
@vogelino can we merge this?

**Comment by vogelino** [comment]
> @vogelino can we merge this?

Do it! :)

**Review by vogelino — APPROVED** [review]

**Pull request merged**
