### PR TITLE
feat/get trees rainfall

### PR DESCRIPTION
**Pull request by ff6347**
This PR adds a api route to get rainfall data per tree. Example call would be 

```bash
curl "http://localhost:3000/api/trees/rainfall?gml_id=s_wfs_baumbestand.00008100:000bc67e" 
```

Will return:

```json
{
  "data": {
    "table": [
      {
        "timestamp": "2022-08-24T00:00:00.000Z",
        "rainfall_in_mm": 0
      },
      {"timestamp": "2022-08-23T00:00:00.000Z", …},
      {"timestamp": "2022-08-22T00:00:00.000Z", …},
      {"timestamp": "2022-08-21T00:00:00.000Z", …},
      {"timestamp": "2022-08-20T00:00:00.000Z", …},
      {"timestamp": "2022-08-19T00:00:00.000Z", …},
      {"timestamp": "2022-08-18T00:00:00.000Z", …},
      {"timestamp": "2022-08-17T00:00:00.000Z", …},
      {"timestamp": "2022-08-16T00:00:00.000Z", …},
      {"timestamp": "2022-08-15T00:00:00.000Z", …},
      {"timestamp": "2022-08-14T00:00:00.000Z", …},
      {"timestamp": "2022-08-13T00:00:00.000Z", …},
      {"timestamp": "2022-08-12T00:00:00.000Z", …},
      {"timestamp": "2022-08-11T00:00:00.000Z", …}
    ],
    "sum_rainfall_in_mm": 22.200000000000003
  }
}



```

### CODE REVIEW

**Review by vogelino — APPROVED** [review]
Great! I don't think we'll need the geojson features for now. We only want to be able to know how many milimeters or liters has rained on a specific tree. We won't show the shape on the map or something. At least in the zivi app. What do you think @dnsos ??

**Comment by dnsos** [comment]
Very nice! I agree, we don't need the geometry, and I don't see it as very likely that we'll need it in the future.

One note that is just stylistic:

How about renaming `weekday` to `timestamp` (since that is what it looks like)? And `daily_rainfall_sum_mm` to `rainfall_in_mm` (since the daily is implied through the timestamp)? What do you think, @ff6347?

**Comment by ff6347** [comment]
Sure. I'll get to it tomorrow

**Comment by vogelino** [comment]
@ff6347 In the response JSON you posted, there are 15 entries. As far as I understand, we want to show in the list how many millimetres of water rained on top of the requested tree in the last 14 days. This means that we yet have to calculate the sum of all entries. Therefore 2 questions:
- Why 15 entries and not 14?
- Could we already calculate the sum in the API route and only get back the sum instead of having to do this in the frontend?

Not sure I'm getting this right. What do you think?

**Comment by ff6347** [comment]
> @ff6347 In the response JSON you posted, there are 15 entries. As far as I understand, we want to show in the list how many millimetres of water rained on top of the requested tree in the last 14 days. This means that we yet have to calculate the sum of all entries. Therefore 2 questions:
> 
>     * Why 15 entries and not 14?

I totally don't know how it became 15. Was a copy pasta error.

> 
>     * Could we already calculate the sum in the API route and only get back the sum instead of having to do this in the frontend?

Added a sum of all data to the result. Since we might display a detailed chart as well I added it instead of making it the only return value.


The result looks like this:

```json
{
  "data": {
    "table": [
      {"timestamp": "2022-08-21T00:00:00.000Z", …},
      {"timestamp": "2022-08-20T00:00:00.000Z", …},
      {"timestamp": "2022-08-19T00:00:00.000Z", …},
      {"timestamp": "2022-08-18T00:00:00.000Z", …},
      {"timestamp": "2022-08-17T00:00:00.000Z", …},
      {"timestamp": "2022-08-16T00:00:00.000Z", …},
      {"timestamp": "2022-08-15T00:00:00.000Z", …},
      {"timestamp": "2022-08-14T00:00:00.000Z", …},
      {"timestamp": "2022-08-13T00:00:00.000Z", …},
      {"timestamp": "2022-08-12T00:00:00.000Z", …},
      {"timestamp": "2022-08-11T00:00:00.000Z", …},
      {"timestamp": "2022-08-10T00:00:00.000Z", …},
      {"timestamp": "2022-08-09T00:00:00.000Z", …},
      {
        "timestamp": "2022-08-08T00:00:00.000Z",
        "rainfall_in_mm": 0
      }
    ],
    "sum_rainfall_in_mm": 22.200000000000003
  }
}
```

**Comment by ff6347** [comment]
There is still some issue going on. The data we see here is two days behind. It is not a problem with the data being outdated in the DB we have data from today in there. I will investigate this issue.

So don't merge it yet

**Comment by ff6347** [comment]
The function no returns the last 14 days 

Response is:

```json
{
  "data": {
    "table": [
      {
        "timestamp": "2022-08-24T00:00:00.000Z",
        "rainfall_in_mm": 0
      },
      {"timestamp": "2022-08-23T00:00:00.000Z", …},
      {"timestamp": "2022-08-22T00:00:00.000Z", …},
      {"timestamp": "2022-08-21T00:00:00.000Z", …},
      {"timestamp": "2022-08-20T00:00:00.000Z", …},
      {"timestamp": "2022-08-19T00:00:00.000Z", …},
      {"timestamp": "2022-08-18T00:00:00.000Z", …},
      {"timestamp": "2022-08-17T00:00:00.000Z", …},
      {"timestamp": "2022-08-16T00:00:00.000Z", …},
      {"timestamp": "2022-08-15T00:00:00.000Z", …},
      {"timestamp": "2022-08-14T00:00:00.000Z", …},
      {"timestamp": "2022-08-13T00:00:00.000Z", …},
      {"timestamp": "2022-08-12T00:00:00.000Z", …},
      {"timestamp": "2022-08-11T00:00:00.000Z", …}
    ],
    "sum_rainfall_in_mm": 22.200000000000003
  }
}
```

**Comment by vogelino** [comment]
Great! Let's merge this right?

**Pull request merged**
